import { queryOne, ensureSchema } from "@/lib/db";
import { createTour } from "@/lib/queries/tours";
import { createNews } from "@/lib/queries/news";
import { createReview } from "@/lib/queries/reviews";
import { ensureSeedAdmin } from "@/lib/auth";

const agents = [
  { agent_name: "คุณนที สายชล", agent_role: "ผู้เชี่ยวชาญทัวร์ภาคเหนือ", agent_photo_url: "https://images.unsplash.com/photo-1633332755192-727a05c4013d?w=300" },
  { agent_name: "คุณมายา ศรีสมุทร", agent_role: "ผู้เชี่ยวชาญทัวร์ภาคใต้ & เกาะ", agent_photo_url: "https://images.unsplash.com/photo-1607346256330-dee7af15f7c5?w=300" },
  { agent_name: "คุณโสภณ ภูมิพนา", agent_role: "ผู้เชี่ยวชาญทัวร์ภาคกลาง-อีสาน", agent_photo_url: "https://images.unsplash.com/photo-1560250097-0b93528c311a?w=300" },
];

const sampleTours = [
  {
    slug: "chiang-mai-hilltribe-trek",
    title: "เชียงใหม่ ป่าเขา และหมู่บ้านชาวเขา 4 วัน 3 คืน",
    category: "เทรคกิ้ง & ธรรมชาติ",
    province: "เชียงใหม่",
    duration_days: 4,
    price: 15900,
    currency: "THB",
    max_group_size: 10,
    difficulty: "ปานกลาง",
    difficulty_rating: 3,
    comfort_rating: 3,
    rating_score: 4.8,
    rating_count: 342,
    rating_source: "TripAdvisor",
    cover_image_url: "https://images.unsplash.com/photo-1528181304800-259b08848526?w=1200",
    gallery: [
      "https://images.unsplash.com/photo-1528181304800-259b08848526?w=1200",
      "https://images.unsplash.com/photo-1552465011-b4e21bf6e79a?w=1200",
    ],
    summary: "เดินป่าเยือนหมู่บ้านชาวเขา ล่องแพไม้ไผ่ และพักโฮมสเตย์กลางธรรมชาติภาคเหนือ",
    description:
      "ทริปนี้พาคุณออกจากเมืองเชียงใหม่สู่ขุนเขา สัมผัสวิถีชีวิตชาวเขาเผ่ากะเหรี่ยงและม้ง เดินป่าชมน้ำตก ล่องแพไม้ไผ่ และพักค้างคืนในโฮมสเตย์ท้องถิ่นแบบดั้งเดิม เหมาะสำหรับผู้ที่รักธรรมชาติและอยากสัมผัสวัฒนธรรมท้องถิ่นอย่างใกล้ชิด",
    itinerary: [
      {
        day: 1,
        title: "เดินทางถึงเชียงใหม่ - หมู่บ้านม้ง",
        description: "รับจากสนามบิน เยี่ยมชมหมู่บ้านม้งดอยปุย พักค้างคืนโฮมสเตย์",
        lunch: true,
        dinner: true,
        accommodation: "โฮมสเตย์ดอยปุย",
        photos: ["https://images.unsplash.com/photo-1552465011-b4e21bf6e79a?w=800"],
        route: [{ from: "สนามบินเชียงใหม่", to: "ดอยปุย", distanceKm: 17, duration: "45 นาที", transport: "รถตู้ปรับอากาศ" }],
      },
      {
        day: 2,
        title: "เดินป่าสู่หมู่บ้านกะเหรี่ยง",
        description: "เดินป่า 6 ชม. ผ่านนาขั้นบันได ถึงหมู่บ้านกะเหรี่ยงคอยาว",
        breakfast: true,
        lunch: true,
        dinner: true,
        accommodation: "โฮมสเตย์หมู่บ้านกะเหรี่ยง",
        route: [{ from: "ดอยปุย", to: "หมู่บ้านกะเหรี่ยง", duration: "เดินป่า 6 ชม.", transport: "เดินเท้า" }],
      },
      {
        day: 3,
        title: "ล่องแพไม้ไผ่ & ขี่ช้างเชิงอนุรักษ์",
        description: "ล่องแพแม่น้ำแตง เยี่ยมชมศูนย์อนุรักษ์ช้าง",
        breakfast: true,
        lunch: true,
        dinner: true,
        accommodation: "รีสอร์ทริมน้ำแตง",
        route: [{ from: "หมู่บ้านกะเหรี่ยง", to: "แม่น้ำแตง", distanceKm: 12, duration: "30 นาที", transport: "รถกระบะท้องถิ่น" }],
      },
      {
        day: 4,
        title: "น้ำตกแม่กลาง - เดินทางกลับ",
        description: "แวะน้ำตกแม่กลาง ส่งสนามบินเชียงใหม่",
        breakfast: true,
        lunch: true,
        route: [{ from: "แม่น้ำแตง", to: "สนามบินเชียงใหม่", distanceKm: 45, duration: "1 ชม.", transport: "รถตู้ปรับอากาศ" }],
      },
    ],
    includes: ["ที่พักตลอดทริป", "อาหารตามระบุในโปรแกรม", "ไกด์ท้องถิ่น", "รถรับส่ง", "ประกันการเดินทาง"],
    excludes: ["ค่าใช้จ่ายส่วนตัว", "ทิปไกด์"],
    highlights: ["โฮมสเตย์ชาวเขาแท้ๆ", "เดินป่าวิวหลักล้าน", "ล่องแพไม้ไผ่"],
    status: "active",
    price_tiers: [
      { groupSize: 2, pricePerPerson: 18900 },
      { groupSize: 4, pricePerPerson: 15900 },
      { groupSize: 6, pricePerPerson: 13500 },
    ],
    hotel_name: "โฮมสเตย์และรีสอร์ทท้องถิ่นภาคเหนือ",
    hotel_description: "ผสมผสานที่พักโฮมสเตย์ชาวเขาแท้ๆ กับรีสอร์ทริมน้ำสไตล์ล้านนา เพื่อประสบการณ์ที่หลากหลายตลอดทริป",
    hotel_images: ["https://images.unsplash.com/photo-1470770903676-69b98201ea1c?w=800"],
    ...agents[0],
    tags: ["สำหรับครอบครัว", "รักธรรมชาติ"],
    tour_code: "THN04",
    hotel_list: [
      { days: "1, 2", city: "เชียงใหม่", name: "โฮมสเตย์ดอยปุย", stars: 0, image: "https://images.unsplash.com/photo-1470770903676-69b98201ea1c?w=600" },
      { days: "3", city: "แม่น้ำแตง", name: "รีสอร์ทริมน้ำแตง", stars: 3, image: "https://images.unsplash.com/photo-1470770903676-69b98201ea1c?w=600" },
    ],
  },
  {
    slug: "koh-samui-island-cruise-3d2n",
    title: "เกาะสมุย ล่องเรือหมู่เกาะอ่างทอง 3 วัน 2 คืน",
    category: "ล่องเรือ & ทะเล",
    province: "สุราษฎร์ธานี",
    duration_days: 3,
    price: 14500,
    currency: "THB",
    max_group_size: 16,
    difficulty: "ง่าย",
    difficulty_rating: 1,
    comfort_rating: 5,
    rating_score: 4.9,
    rating_count: 587,
    rating_source: "TripAdvisor",
    cover_image_url: "https://images.unsplash.com/photo-1528127269322-539801943592?w=1200",
    gallery: ["https://images.unsplash.com/photo-1528127269322-539801943592?w=1200"],
    summary: "ล่องเรือชมอุทยานแห่งชาติหมู่เกาะอ่างทอง มรดกทางธรรมชาติของอ่าวไทย พร้อมกิจกรรมพายเรือคายัคและดำน้ำตื้น",
    description:
      "พักผ่อนบนเกาะสมุย ล่องเรือชมโขดหินปูนกลางทะเลอ่าวไทยที่หมู่เกาะอ่างทอง พายเรือคายัคเข้าอ่าวลับ ชมทะเลสาบสีมรกตบนเกาะแม่เกาะ และดำน้ำตื้นชมปะการังน้ำใส",
    itinerary: [
      {
        day: 1,
        title: "เดินทางถึงเกาะสมุย - หาดเฉวง",
        description: "เช็คอินที่พัก พักผ่อนชายหาด ชมพระอาทิตย์ตกริมทะเล",
        lunch: true,
        dinner: true,
        accommodation: "รีสอร์ทหาดเฉวง",
        photos: ["https://images.unsplash.com/photo-1528127269322-539801943592?w=800"],
        route: [{ from: "สนามบินสมุย", to: "หาดเฉวง", distanceKm: 8, duration: "20 นาที", transport: "รถรับส่งส่วนตัว" }],
      },
      {
        day: 2,
        title: "ล่องเรือหมู่เกาะอ่างทอง - พายเรือคายัค",
        description: "ล่องเรือชมหมู่เกาะอ่างทอง พายคายัคเข้าอ่าวลับ ดำน้ำตื้นชมปะการัง",
        breakfast: true,
        lunch: true,
        dinner: true,
        accommodation: "รีสอร์ทหาดเฉวง",
      },
      {
        day: 3,
        title: "วัดพระใหญ่ - เดินทางกลับ",
        description: "แวะชมวัดพระใหญ่ ช้อปของฝาก ส่งสนามบินสมุย",
        breakfast: true,
        route: [{ from: "หาดเฉวง", to: "สนามบินสมุย", distanceKm: 8, duration: "20 นาที", transport: "รถรับส่งส่วนตัว" }],
      },
    ],
    includes: ["ที่พักตลอดทริป", "อาหารตามระบุในโปรแกรม", "ล่องเรือหมู่เกาะอ่างทอง", "อุปกรณ์คายัคและดำน้ำตื้น", "ไกด์ท้องถิ่น"],
    excludes: ["ตั๋วเครื่องบิน", "ค่าธรรมเนียมอุทยานแห่งชาติ", "เครื่องดื่มแอลกอฮอล์"],
    highlights: ["ล่องเรือมรดกทางธรรมชาติอ่างทอง", "คายัคเข้าอ่าวลับ", "ทะเลสาบสีมรกต"],
    status: "active",
    price_tiers: [
      { groupSize: 2, pricePerPerson: 17900 },
      { groupSize: 4, pricePerPerson: 14500 },
      { groupSize: 6, pricePerPerson: 12500 },
    ],
    hotel_name: "รีสอร์ทหาดเฉวง เกาะสมุย",
    hotel_description: "ห้องพักวิวทะเลริมหาดเฉวง พร้อมสระว่ายน้ำและร้านอาหารในรีสอร์ท",
    hotel_images: ["https://images.unsplash.com/photo-1528127269322-539801943592?w=800"],
    ...agents[1],
    tags: ["สำหรับคู่รัก", "กลุ่มเพื่อน"],
    tour_code: "THN08",
    hotel_list: [
      { days: "1, 2, 3", city: "เกาะสมุย", name: "รีสอร์ทหาดเฉวง", stars: 4, image: "https://images.unsplash.com/photo-1528127269322-539801943592?w=600" },
    ],
  },
  {
    slug: "sukhothai-heritage-explorer-3d2n",
    title: "สุโขทัย มรดกโลกอุทยานประวัติศาสตร์ 3 วัน 2 คืน",
    category: "วัฒนธรรม & ประวัติศาสตร์",
    province: "สุโขทัย",
    duration_days: 3,
    price: 8900,
    currency: "THB",
    max_group_size: 14,
    difficulty: "ง่าย",
    difficulty_rating: 2,
    comfort_rating: 4,
    rating_score: 4.7,
    rating_count: 421,
    rating_source: "TripAdvisor",
    cover_image_url: "https://images.unsplash.com/photo-1508009603885-50cf7c079365?w=1200",
    gallery: ["https://images.unsplash.com/photo-1508009603885-50cf7c079365?w=1200"],
    summary: "สัมผัสอารยธรรมสุโขทัย ชมพระอาทิตย์ขึ้นที่อุทยานประวัติศาสตร์และเมืองเก่าศรีสัชนาลัย",
    description:
      "เยือนราชธานีแห่งแรกของไทย ชมความยิ่งใหญ่ของอุทยานประวัติศาสตร์สุโขทัยและศรีสัชนาลัย มรดกโลกทางวัฒนธรรม พร้อมปั่นจักรยานชมซากปรักหักพังยามเช้าและเที่ยวชมตลาดโบราณริมน้ำยม",
    itinerary: [
      {
        day: 1,
        title: "เดินทางถึงสุโขทัย - ตลาดเช้าเมืองเก่า",
        description: "เช็คอินที่พัก เดินเที่ยวตลาดเช้าและชุมชนริมน้ำยม",
        lunch: true,
        dinner: true,
        accommodation: "โรงแรม 3 ดาว ใจกลางสุโขทัย",
      },
      {
        day: 2,
        title: "อุทยานประวัติศาสตร์สุโขทัย - ศรีสัชนาลัย",
        description: "ปั่นจักรยานชมวัดมหาธาตุยามเช้า เดินทางต่อชมอุทยานประวัติศาสตร์ศรีสัชนาลัย",
        breakfast: true,
        lunch: true,
        dinner: true,
        accommodation: "โรงแรม 3 ดาว ใจกลางสุโขทัย",
        photos: ["https://images.unsplash.com/photo-1508009603885-50cf7c079365?w=800"],
        route: [
          { from: "สุโขทัย", to: "อุทยานประวัติศาสตร์สุโขทัย", distanceKm: 12, duration: "20 นาที", transport: "รถตู้ปรับอากาศ" },
          { from: "อุทยานประวัติศาสตร์สุโขทัย", to: "ศรีสัชนาลัย", distanceKm: 55, duration: "1 ชม.", transport: "รถตู้ปรับอากาศ" },
        ],
      },
      {
        day: 3,
        title: "วัดศรีชุม - เดินทางกลับ",
        description: "แวะชมวัดศรีชุมและพระอจนะ ช้อปของฝากพื้นเมือง เดินทางกลับ",
        breakfast: true,
      },
    ],
    includes: ["ที่พัก 3 ดาว", "อาหารตามระบุ", "ค่าเข้าชมอุทยานประวัติศาสตร์", "จักรยานเช่า", "ไกด์ท้องถิ่น"],
    excludes: ["ค่าเดินทางส่วนตัว", "ทิปไกด์และคนขับ"],
    highlights: ["พระอาทิตย์ขึ้นวัดมหาธาตุ", "อุทยานประวัติศาสตร์ศรีสัชนาลัย", "ปั่นจักรยานชมเมืองโบราณ"],
    status: "active",
    price_tiers: [
      { groupSize: 2, pricePerPerson: 10900 },
      { groupSize: 4, pricePerPerson: 8900 },
      { groupSize: 6, pricePerPerson: 7500 },
    ],
    hotel_name: "โรงแรมใจกลางสุโขทัย",
    hotel_description: "ที่พัก 3 ดาว เดินทางสะดวกใกล้ตลาดเย็นและร้านอาหารท้องถิ่น",
    hotel_images: ["https://images.unsplash.com/photo-1590490360182-c33d57733427?w=800"],
    ...agents[2],
    tags: ["สำหรับครอบครัว", "กลุ่มเพื่อน"],
    tour_code: "THN03",
    map_embed_url:
      "https://maps.google.com/maps?q=Sukhothai%20Historical%20Park%2C%20Thailand&z=12&output=embed",
    hotel_list: [
      { days: "1, 2, 3", city: "สุโขทัย", name: "โรงแรม 3 ดาว ใจกลางเมือง", stars: 3, image: "https://images.unsplash.com/photo-1590490360182-c33d57733427?w=600" },
    ],
  },
  {
    slug: "nan-slowlife-3d2n",
    title: "น่าน สโลว์ไลฟ์ เมืองสงบกลางขุนเขา 3 วัน 2 คืน",
    category: "วัฒนธรรม & ประวัติศาสตร์",
    province: "น่าน",
    duration_days: 3,
    price: 9500,
    currency: "THB",
    max_group_size: 12,
    difficulty: "ง่าย",
    difficulty_rating: 1,
    comfort_rating: 4,
    rating_score: 4.9,
    rating_count: 298,
    rating_source: "TripAdvisor",
    cover_image_url: "https://images.unsplash.com/photo-1548544149-4835e62ee5b3?w=1200",
    gallery: ["https://images.unsplash.com/photo-1548544149-4835e62ee5b3?w=1200"],
    summary: "ชมจิตรกรรมกระซิบรักที่วัดภูมินทร์ ชมทะเลหมอกดอยเสมอดาว และดื่มด่ำเมืองเก่าน่านแบบสโลว์ไลฟ์",
    description:
      "เมืองน่านเมืองเล็กๆ กลางขุนเขาที่เวลาเดินช้าลง ชมจิตรกรรมฝาผนัง 'กระซิบรัก' อันโด่งดังที่วัดภูมินทร์ นมัสการพระธาตุแช่แห้ง ปั่นจักรยานชมเมืองเก่า และชมทะเลหมอกยามเช้าที่ดอยเสมอดาว",
    itinerary: [
      { day: 1, title: "ถึงน่าน - วัดภูมินทร์", description: "ชมจิตรกรรมกระซิบรักที่วัดภูมินทร์ เดินเล่นเมืองเก่า", dinner: true, accommodation: "เกสต์เฮาส์ริมแม่น้ำน่าน" },
      {
        day: 2,
        title: "ดอยเสมอดาว - พระธาตุแช่แห้ง",
        description: "ชมทะเลหมอกยามเช้าที่ดอยเสมอดาว นมัสการพระธาตุแช่แห้ง",
        breakfast: true,
        lunch: true,
        dinner: true,
        accommodation: "เกสต์เฮาส์ริมแม่น้ำน่าน",
        photos: ["https://images.unsplash.com/photo-1548544149-4835e62ee5b3?w=800"],
        route: [{ from: "น่าน", to: "ดอยเสมอดาว", distanceKm: 45, duration: "1 ชม.", transport: "รถตู้ท้องถิ่น" }],
      },
      { day: 3, title: "ตลาดเช้าน่าน - เดินทางกลับ", description: "เดินตลาดเช้า ช้อปของฝากพื้นเมือง เดินทางกลับ", breakfast: true },
    ],
    includes: ["ที่พักใจกลางเมือง", "อาหารเช้าทุกวัน", "รถรับส่งสนามบิน", "ไกด์ท้องถิ่น"],
    excludes: ["อาหารกลางวัน-เย็นบางมื้อ", "ค่าใช้จ่ายส่วนตัว"],
    highlights: ["จิตรกรรมกระซิบรักวัดภูมินทร์", "ทะเลหมอกดอยเสมอดาว", "เมืองเก่าริมแม่น้ำน่าน"],
    status: "active",
    price_tiers: [
      { groupSize: 2, pricePerPerson: 11500 },
      { groupSize: 4, pricePerPerson: 9500 },
      { groupSize: 6, pricePerPerson: 8200 },
    ],
    hotel_name: "เกสต์เฮาส์ริมแม่น้ำน่าน",
    hotel_description: "บรรยากาศสงบริมแม่น้ำน่าน เดินถึงตลาดเช้าและวัดสำคัญได้",
    hotel_images: ["https://images.unsplash.com/photo-1548544149-4835e62ee5b3?w=800"],
    ...agents[2],
    tags: ["สำหรับคู่รัก", "รักธรรมชาติ"],
    tour_code: "THN11",
    hotel_list: [
      { days: "1, 2, 3", city: "น่าน", name: "เกสต์เฮาส์ริมแม่น้ำน่าน", stars: 3, image: "https://images.unsplash.com/photo-1548544149-4835e62ee5b3?w=600" },
    ],
  },
  {
    slug: "khaoyai-balloon-sunrise-3d2n",
    title: "เขาใหญ่ บอลลูนชมทะเลหมอก 3 วัน 2 คืน",
    category: "ผจญภัย & มุมกล้อง",
    province: "นครราชสีมา",
    duration_days: 3,
    price: 12900,
    currency: "THB",
    max_group_size: 8,
    difficulty: "ง่าย",
    difficulty_rating: 2,
    comfort_rating: 4,
    rating_score: 4.8,
    rating_count: 176,
    rating_source: "TripAdvisor",
    cover_image_url: "https://images.unsplash.com/photo-1553603227-2358aabe821e?w=1200",
    gallery: ["https://images.unsplash.com/photo-1553603227-2358aabe821e?w=1200"],
    summary: "ขึ้นบอลลูนชมทะเลหมอกยามเช้าเหนือเขาใหญ่ พร้อมชิมไวน์ไทยและซาฟารีสัตว์ป่า",
    description:
      "ทริปสายถ่ายภาพและผจญภัยสุดพิเศษ ล่องบอลลูนลอยฟ้าชมทะเลหมอกเหนือเทือกเขาเขาใหญ่ยามเช้า ชมไร่องุ่นและชิมไวน์ไทยที่ไร่ PB Valley ตื่นเต้นกับซาฟารีชมสัตว์ป่ายามเย็น และเดินป่าชมน้ำตกเหวสุวัต",
    itinerary: [
      { day: 1, title: "เดินทางถึงเขาใหญ่ - ไร่องุ่น PB Valley", description: "เช็คอินที่พัก ชมไร่องุ่นและชิมไวน์ไทย พระอาทิตย์ตกเหนือทุ่งองุ่น", dinner: true, accommodation: "รีสอร์ทเขาใหญ่" },
      {
        day: 2,
        title: "บอลลูนชมทะเลหมอก - ซาฟารีเขาใหญ่",
        description: "ขึ้นบอลลูนแต่เช้ามืดชมทะเลหมอกเหนือเทือกเขา ตื่นเต้นกับซาฟารีชมสัตว์ป่ายามเย็น",
        breakfast: true,
        lunch: true,
        dinner: true,
        accommodation: "รีสอร์ทเขาใหญ่",
        photos: ["https://images.unsplash.com/photo-1553603227-2358aabe821e?w=800"],
      },
      { day: 3, title: "น้ำตกเหวสุวัต - เดินทางกลับ", description: "เดินป่าชมน้ำตกเหวสุวัต อิสระช้อปปิ้งของฝาก เดินทางกลับ", breakfast: true, lunch: true },
    ],
    includes: ["ค่าบอลลูน", "ที่พักรีสอร์ท", "ค่าเข้าอุทยานแห่งชาติเขาใหญ่", "ไกด์ท้องถิ่น"],
    excludes: ["ค่าชิมไวน์เพิ่มเติม", "ทิป"],
    highlights: ["บอลลูนทะเลหมอกเขาใหญ่", "ชิมไวน์ไร่ PB Valley", "ซาฟารีชมสัตว์ป่า"],
    status: "active",
    price_tiers: [
      { groupSize: 2, pricePerPerson: 15900 },
      { groupSize: 4, pricePerPerson: 12900 },
      { groupSize: 6, pricePerPerson: 11200 },
    ],
    hotel_name: "รีสอร์ทเขาใหญ่",
    hotel_description: "ห้องพักท่ามกลางธรรมชาติ วิวเทือกเขาเขาใหญ่ พร้อมสระว่ายน้ำกลางแจ้ง",
    hotel_images: ["https://images.unsplash.com/photo-1553603227-2358aabe821e?w=800"],
    ...agents[1],
    tags: ["สำหรับคู่รัก", "กลุ่มเพื่อน"],
    tour_code: "THN07",
    video_url: "https://youtube.com",
    hotel_list: [
      { days: "1, 2, 3", city: "เขาใหญ่", name: "รีสอร์ทเขาใหญ่", stars: 4, image: "https://images.unsplash.com/photo-1553603227-2358aabe821e?w=600" },
    ],
  },
  {
    slug: "phuket-island-hopping-3d2n",
    title: "ภูเก็ต ล่องเกาะพีพี & เจมส์บอนด์ 3 วัน 2 คืน",
    category: "ล่องเรือ & ทะเล",
    province: "ภูเก็ต",
    duration_days: 3,
    price: 9900,
    currency: "THB",
    max_group_size: 20,
    difficulty: "ง่าย",
    difficulty_rating: 1,
    comfort_rating: 4,
    rating_score: 4.6,
    rating_count: 812,
    rating_source: "TripAdvisor",
    cover_image_url: "https://images.unsplash.com/photo-1589394815804-964ed0be2eb5?w=1200",
    gallery: ["https://images.unsplash.com/photo-1589394815804-964ed0be2eb5?w=1200"],
    summary: "ดำน้ำตื้นน้ำใสที่เกาะพีพี ถ่ายรูปเก๋ๆ ที่เกาะเจมส์บอนด์ พักผ่อนหาดทรายขาว",
    description: "ทริปทะเลยอดนิยม ล่องเรือสปีดโบ๊ทเที่ยวเกาะพีพี เกาะไข่ อ่าวพังงา และเกาะเจมส์บอนด์ พร้อมกิจกรรมดำน้ำตื้นชมปะการัง",
    itinerary: [
      { day: 1, title: "ถึงภูเก็ต - หาดป่าตอง", description: "เช็คอินที่พัก พักผ่อนชายหาด", dinner: true, accommodation: "รีสอร์ทหาดป่าตอง" },
      {
        day: 2,
        title: "เกาะพีพี - เกาะไข่",
        description: "ล่องเรือสปีดโบ๊ท ดำน้ำตื้น อ่าวมาหยา",
        breakfast: true,
        lunch: true,
        accommodation: "รีสอร์ทหาดป่าตอง",
        photos: ["https://images.unsplash.com/photo-1589394815804-964ed0be2eb5?w=800"],
        route: [{ from: "ภูเก็ต", to: "เกาะพีพี", duration: "1.5 ชม.", transport: "เรือสปีดโบ๊ท" }],
      },
      { day: 3, title: "อ่าวพังงา - เกาะเจมส์บอนด์", description: "ล่องเรือแคนู ถ่ายรูปเกาะเจมส์บอนด์ เดินทางกลับ", breakfast: true, lunch: true },
    ],
    includes: ["ที่พัก 2 คืน", "เรือสปีดโบ๊ท", "อุปกรณ์ดำน้ำตื้น", "อาหารกลางวัน"],
    excludes: ["ตั๋วเครื่องบิน", "ค่าธรรมเนียมอุทยานแห่งชาติ", "เครื่องดื่ม"],
    highlights: ["อ่าวมาหยาในตำนาน", "เกาะเจมส์บอนด์", "ดำน้ำตื้นน้ำใส"],
    status: "active",
    price_tiers: [
      { groupSize: 2, pricePerPerson: 12500 },
      { groupSize: 4, pricePerPerson: 9900 },
      { groupSize: 6, pricePerPerson: 8400 },
    ],
    hotel_name: "รีสอร์ทหาดป่าตอง",
    hotel_description: "รีสอร์ทริมหาดป่าตอง เดินถึงร้านอาหารและไนท์ไลฟ์ได้สะดวก",
    hotel_images: ["https://images.unsplash.com/photo-1589394815804-964ed0be2eb5?w=800"],
    ...agents[0],
    tags: ["สำหรับครอบครัว", "สำหรับคู่รัก", "กลุ่มเพื่อน"],
    tour_code: "THN09",
    hotel_list: [
      { days: "1, 2, 3", city: "ภูเก็ต", name: "รีสอร์ทหาดป่าตอง", stars: 4, image: "https://images.unsplash.com/photo-1589394815804-964ed0be2eb5?w=600" },
    ],
  },
];

const sampleNews = [
  {
    slug: "welcome-new-website",
    title: "เปิดตัวเว็บไซต์ใหม่พร้อมระบบจองทัวร์ออนไลน์",
    excerpt: "จองทัวร์ง่ายขึ้นกว่าเดิม พร้อมระบบแจ้งเตือนทางอีเมลอัตโนมัติ",
    content:
      "เราภูมิใจนำเสนอเว็บไซต์ใหม่ที่ออกแบบมาเพื่อให้การจองทัวร์ของคุณง่ายและรวดเร็วยิ่งขึ้น พร้อมระบบยืนยันการจองผ่านอีเมลทันที",
    cover_image_url: "https://images.unsplash.com/photo-1488646953014-85cb44e25828?w=1200",
    published: true,
  },
  {
    slug: "best-time-to-visit-thailand",
    title: "ช่วงเวลาที่ดีที่สุดในการเที่ยวแต่ละภาคของไทย",
    excerpt: "แนะนำเดือนที่เหมาะกับการเที่ยวแต่ละภูมิภาค เพื่อทริปในประเทศที่สมบูรณ์แบบ",
    content:
      "ประเทศไทยมีสภาพอากาศหลากหลายตามแต่ละภูมิภาค บทความนี้จะพาไปดูว่าควรไปเที่ยวภาคไหนช่วงเดือนใดถึงจะได้บรรยากาศที่ดีที่สุด ทั้งภาคเหนือ ภาคใต้ และภาคอีสาน",
    cover_image_url: "https://images.unsplash.com/photo-1552733407-5d5c46c3bb3b?w=1200",
    published: true,
  },
];

const sampleReviews = [
  {
    customer_name: "คุณศิริพร ว.",
    customer_country: "กรุงเทพฯ ประเทศไทย",
    customer_photo_url: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=200",
    rating: 5,
    title: "ทริปเชียงใหม่ที่ประทับใจที่สุด",
    quote: "ไกด์ท้องถิ่นรู้ลึกจริง พาไปในที่ที่ไม่มีในกูเกิล ทีมงานตอบไวและดูแลดีมากตลอดทริป ประทับใจสุดๆ",
    travel_dates: "ธันวาคม 2568",
    featured: true,
  },
  {
    customer_name: "Alex Tanner",
    customer_country: "Australia",
    customer_photo_url: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200",
    rating: 5,
    title: "Koh Samui island cruise was unforgettable",
    quote: "The whole trip was seamless from booking to the actual cruise. Our request for a quote was answered within hours and the itinerary was perfectly tailored.",
    travel_dates: "October 2025",
    featured: true,
  },
  {
    customer_name: "คุณวรากร ป.",
    customer_country: "เชียงใหม่ ประเทศไทย",
    customer_photo_url: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=200",
    rating: 4,
    title: "ทัวร์ตามสั่งได้จริง",
    quote: "ขอปรับโปรแกรมหลายรอบจนลงตัว ทีมงานอดทนตอบทุกคำถาม สุดท้ายได้ทริปที่ตรงใจครอบครัวมาก",
    travel_dates: "กุมภาพันธ์ 2569",
    featured: true,
  },
];

export async function seedIfEmpty() {
  await ensureSchema();
  const countRow = await queryOne<{ c: string }>("SELECT COUNT(*) as c FROM tours");
  if (Number(countRow?.c || 0) === 0) {
    for (const t of sampleTours) await createTour(t as any);
  }
  const newsRow = await queryOne<{ c: string }>("SELECT COUNT(*) as c FROM news");
  if (Number(newsRow?.c || 0) === 0) {
    for (const n of sampleNews) await createNews(n as any);
  }
  const reviewRow = await queryOne<{ c: string }>("SELECT COUNT(*) as c FROM reviews");
  if (Number(reviewRow?.c || 0) === 0) {
    for (const r of sampleReviews) await createReview(r as any);
  }
  await ensureSeedAdmin();
}
